create table if not exists public.leagues (
  id text primary key,
  name text not null check (char_length(name) between 1 and 32),
  pin_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  league_id text not null references public.leagues(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 18),
  seed integer not null check (seed >= 0),
  unique (league_id, name),
  unique (league_id, seed)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  league_id text not null references public.leagues(id) on delete cascade,
  round integer not null check (round > 0),
  home_team_id bigint not null references public.teams(id) on delete cascade,
  away_team_id bigint not null references public.teams(id) on delete cascade,
  home_score integer check (home_score between 0 and 99),
  away_score integer check (away_score between 0 and 99),
  updated_at timestamptz not null default now(),
  unique (league_id, round),
  check (home_team_id <> away_team_id),
  check (
    (home_score is null and away_score is null)
    or (home_score is not null and away_score is not null)
  )
);

create index if not exists teams_league_idx
  on public.teams (league_id);

create index if not exists matches_league_idx
  on public.matches (league_id);

alter table public.leagues enable row level security;
alter table public.teams enable row level security;
alter table public.matches enable row level security;

revoke all on table public.leagues from anon, authenticated;
revoke all on table public.teams from anon, authenticated;
revoke all on table public.matches from anon, authenticated;

revoke all on sequence public.teams_id_seq from anon, authenticated;
revoke all on sequence public.matches_id_seq from anon, authenticated;
